'use client';
import { usePathname } from 'next/navigation';
import { Inter } from 'next/font/google';
import './globals.css';
import type { ReactNode } from 'react';
import SideNav from '@/components/sideNav/sideNav';
import Header from '@/components/header/header';

const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

interface RootLayoutProps {
  children: ReactNode;
  showSideNav?: boolean;
}

export default function RootLayout({
  children,
  showSideNav = false,
}: RootLayoutProps) {

  const pathname = usePathname();
  
  return (
    <html lang="en">
      <body>
        {pathname == '/login' || pathname == '/' ? (
          <div>{children}</div>
        ) : (
          <div className="layoutContainer">
            <SideNav />

            <div className="contentContainer">
              
              {children}
              </div>
          </div>
        )}
      </body>
    </html>
  );
}
